/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuRouteImport } from './routes/ru'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QrRouteImport } from './routes/qr'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as RuPSlugRouteImport } from './routes/ru.p.$slug'
import { Route as QrPSlugRouteImport } from './routes/qr.p.$slug'
import { Route as EnPSlugRouteImport } from './routes/en.p.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuPSlugRoute = RuPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => RuRoute,
} as any)
const QrPSlugRoute = QrPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => QrRoute,
} as any)
const EnPSlugRoute = EnPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/en/p/$slug': typeof EnPSlugRoute
  '/qr/p/$slug': typeof QrPSlugRoute
  '/ru/p/$slug': typeof RuPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/en/p/$slug': typeof EnPSlugRoute
  '/qr/p/$slug': typeof QrPSlugRoute
  '/ru/p/$slug': typeof RuPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/qr': typeof QrRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$slug': typeof PSlugRoute
  '/en/p/$slug': typeof EnPSlugRoute
  '/qr/p/$slug': typeof QrPSlugRoute
  '/ru/p/$slug': typeof RuPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/qr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/en/p/$slug'
    | '/qr/p/$slug'
    | '/ru/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/qr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/en/p/$slug'
    | '/qr/p/$slug'
    | '/ru/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/qr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/p/$slug'
    | '/en/p/$slug'
    | '/qr/p/$slug'
    | '/ru/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRouteWithChildren
  QrRoute: typeof QrRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RuRoute: typeof RuRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/p/$slug': {
      id: '/ru/p/$slug'
      path: '/p/$slug'
      fullPath: '/ru/p/$slug'
      preLoaderRoute: typeof RuPSlugRouteImport
      parentRoute: typeof RuRoute
    }
    '/qr/p/$slug': {
      id: '/qr/p/$slug'
      path: '/p/$slug'
      fullPath: '/qr/p/$slug'
      preLoaderRoute: typeof QrPSlugRouteImport
      parentRoute: typeof QrRoute
    }
    '/en/p/$slug': {
      id: '/en/p/$slug'
      path: '/p/$slug'
      fullPath: '/en/p/$slug'
      preLoaderRoute: typeof EnPSlugRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface EnRouteChildren {
  EnPSlugRoute: typeof EnPSlugRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnPSlugRoute: EnPSlugRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface QrRouteChildren {
  QrPSlugRoute: typeof QrPSlugRoute
}

const QrRouteChildren: QrRouteChildren = {
  QrPSlugRoute: QrPSlugRoute,
}

const QrRouteWithChildren = QrRoute._addFileChildren(QrRouteChildren)

interface RuRouteChildren {
  RuPSlugRoute: typeof RuPSlugRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuPSlugRoute: RuPSlugRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRouteWithChildren,
  QrRoute: QrRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RuRoute: RuRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
